export const auth = {
  LOAD_USER_REQUEST: 'LOAD_USER_REQUEST',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOG_OUT_REQUEST: 'LOG_OUT_REQUEST',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  ACCOUNT_DELETED_REQUEST: 'ACCOUNT_DELETED_REQUEST',
  ACCOUNT_DELETED_SUCCESS: 'ACCOUNT_DELETED_SUCCESS',
  ACCOUNT_DELETED_FAILURE: 'ACCOUNT_DELETED_FAILURE',
  AUTH_ERROR: 'AUTH_ERROR'
};

export const alert = {
  SET_ALERT_REQUEST: 'SET_ALERT_REQUEST',
  SET_ALERT_SUCCESS: 'SET_ALERT_SUCCESS',
  REMOVE_ALERT_SUCCESS: 'REMOVE_ALERT_SUCCESS'
};

export const profile = {
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

  GET_PROFILES_REQUEST: 'GET_PROFILES_REQUEST',
  GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
  GET_PROFILES_FAILURE: 'GET_PROFILES_FAILURE',

  CLEAR_PROFILE_REQUEST: 'CLEAR_PROFILE_REQUEST',
  CLEAR_PROFILE_SUCCESS: 'CLEAR_PROFILE_SUCCESS',
  CLEAR_PROFILE_FAILURE: 'CLEAR_PROFILE_FAILURE',

  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  DELETE_ACCOUNT_REQUEST: 'DELETE_ACCOUNT_REQUEST',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_ACCOUNT_FAILURE: 'DELETE_ACCOUNT_FAILURE',

  GET_REPOS_REQUEST: 'GET_REPOS_REQUEST',
  GET_REPOS_SUCCESS: 'GET_REPOS_SUCCESS',
  GET_REPOS_FAILURE: 'GET_REPOS_FAILURE'
};