export const auth = {
  LOAD_USER_REQUEST: 'LOAD_USER_REQUEST',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOG_OUT_REQUEST: 'LOG_OUT_REQUEST',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
  ACCOUNT_DELETED_REQUEST: 'ACCOUNT_DELETED_REQUEST',
  ACCOUNT_DELETED_SUCCESS: 'ACCOUNT_DELETED_SUCCESS',
  ACCOUNT_DELETED_FAILURE: 'ACCOUNT_DELETED_FAILURE',
  AUTH_ERROR: 'AUTH_ERROR'
};
